# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a44c7a988e93b264c3dcaf7ff14989668ca928e84263396286d484ae348fbd640c0992c0981f7c856b7d5adcaca9d0d7ac08ceece045beda23df83d9c8b25c50

test:
  secret_key_base: 9f4ff0e722a8a9eeb542e6f680e2a7f6c8458cf2d7f492419c50afa3cd53fbbcf45e75c3b4e57b99580752d4a45f1ce7ad8cb00bfd3c1c8b23d779aa732eba94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
